# Sidebar navigation

- label: 'Introduction'
  items:
    - label: 'What is Model Cards Plus?'
      link: /mc+/what-is-mc+
    - label: 'What are cards?'
      link: /mc+/what-are-cards
    - label: 'Why did we create MC+?'
      link: /mc+/why-mc+
    - label: 'How have we developed MC+?'
      link: /mc+/how-have-we-developed-mc+
    - label: 'What could MC+ offer me?'
      link: /mc+/what-could-mc+offer-me

- label: 'Using MC+'
  items:
    - label: 'How do the three MC+ cards work together?'
      link: /mc+/working-together
    - label: 'Who can use MC+?'
      link: /mc+/who-can-use-mc+
    - label: 'What information does MC+ capture?'
      link: /mc+/what-information-capture
    - label: 'How much information does MC+ require?'
      link: /mc+/how-much-information-capture
    - label: 'What types of technology does MC+ cover?'
      link: /mc+/what-types-of-technology
    - label: 'How and when should I use MC+?'
      link: /mc+/how-and-when-should-i-use-mc+
    - label: 'Could I use other types of cards with MC+?'
      link: /mc+/other-types-of-cards

- label: 'MC+ in context'
  items:
    - label: 'Example use'
      link: /mc+/example

# - label: 'Getting Started'
#   items: 
#     - label: 'Introduction'
#       link: '/'
#     - label: 'Getting started'
#       link: '/getting-started'
# - label: Usage
#   items:
#     - label: 'Creating docs'
#       link: '/usage/creating-docs'
#     - label: 'Navigation'
#       link: '/usage/navigation'
#     - label: 'Customizing'
#       link: '/usage/customizing'
#     - label: 'Using YAML files'
#       link: '/usage/using-yaml-files'
#     - label: 'Remark Plugins'
#       link: '/usage/remark-plugins'
# - label: More
#   items:
#     - label: FAQ
#       link: /faq
#     - label: 'Github'
#       link: https://github.com/jpedroschmitz/rocketdocs

