# Sidebar navigation

- label: Home
  link: /

- label: 'About'
  items:
    - label: 'What is MC+?'
      link: /mc+/what-is-mc+
    - label: 'Background'
      link: /mc+/background
    - label: 'The MC+ framework'
      link: /mc+/framework
    - label: 'Who can use MC+?'
      link: /mc+/who-can-use-mc+  
    # - label: 'Test plot'
    #   link: /mc+/test-plot


- label: 'Using MC+'
  items:
    - label: 'For developers'
      link: /mc+/who-can-use-mc+/developers
    - label: 'For researchers'
      link: /mc+/who-can-use-mc+/researchers
    - label: 'For policymakers'
      link: /mc+/who-can-use-mc+/public
    - label: 'For commercial' 
    - label: 'What could MC+ offer me?'
      link: /mc+/what-could-mc+offer-me
    # - label: 'MC+ for policy'
    #   link: /mc+/what-could-mc+offer-me
    # - label: 'MC+ for governance'
    #   link: /mc+/what-could-mc+offer-me
    - label: 'FAQs'
      link: /mc+/faqs

- label: 'Resources'
  items:
    - label: 'Dataset Card'
      link: /mc+/dataset-card
    - label: 'Model Card'
    - label: 'System Card'

- label: 'Further Information'
  items:
    - label: 'Example use'
      link: /mc+/example
    - label: 'Contact'
      link: /mc+/contact
    - label: 'Acknowledgements'

# - label: 'Getting Started'
#   items: 
#     - label: 'Introduction'
#       link: '/'
#     - label: 'Getting started'
#       link: '/getting-started'
# - label: Usage
#   items:
#     - label: 'Creating docs'
#       link: '/usage/creating-docs'
#     - label: 'Navigation'
#       link: '/usage/navigation'
#     - label: 'Customizing'
#       link: '/usage/customizing'
#     - label: 'Using YAML files'
#       link: '/usage/using-yaml-files'
#     - label: 'Remark Plugins'
#       link: '/usage/remark-plugins'
# - label: More
#   items:
#     - label: FAQ
#       link: /faq
#     - label: 'Github'
#       link: https://github.com/jpedroschmitz/rocketdocs

